<?php

/**
 * @file
 * Necessary file for declaring the Rules examples module. See
 * rules_braintree.rules.inc for the actual rules plugins.
 */

/**
 * Implements of hook_cb_subscription_charged_unsuccessfully().
 */
function rules_braintree_cb_subscription_canceled($user, $sid) {
  $planid = commerce_braintree_planid_get_by_sid($sid);
  rules_invoke_event('rules_braintree_event_subscription_canceled', $user, $planid);
}

/**
 * Implements of hook_cb_subscription_charged_unsuccessfully().
 */
function rules_braintree_cb_subscription_charged_successfully($user, $sid) {
  $planid = commerce_braintree_planid_get_by_sid($sid);
  rules_invoke_event('rules_braintree_event_subscription_charged_successfully', $user, $planid);
}

/**
 * Implements of hook_cb_subscription_charged_unsuccessfully().
 */
function rules_braintree_cb_subscription_charged_unsuccessfully($user, $sid) {
  $planid = commerce_braintree_planid_get_by_sid($sid);
  rules_invoke_event('rules_braintree_event_subscription_charged_unsuccessfully', $user, $planid);
}

/**
 * Implements of hook_cb_subscription_expired().
 */
function rules_braintree_cb_subscription_expired($user, $sid) {
  $planid = commerce_braintree_planid_get_by_sid($sid);
  rules_invoke_event('rules_braintree_event_subscription_expired', $user, $planid);
}

/**
 * Implements of hook_cb_subscription_trial_ended().
 */
function rules_braintree_cb_subscription_trial_ended($user, $sid) {
  rules_invoke_event('rules_braintree_event_subscription_trial_ended', $user, $planid);
}

/**
 * Implements of hook_cb_subscription_went_past_due().
 */
function rules_braintree_cb_subscription_went_past_due($user, $sid) {
  $planid = commerce_braintree_planid_get_by_sid($sid);
  rules_invoke_event('rules_braintree_event_subscription_went_past_due', $user, $planid);
}

/**
 * Implements of hook_cb_subscription_went_active().
 */
function rules_braintree_cb_subscription_went_active($user, $sid) {
  $planid = commerce_braintree_planid_get_by_sid($sid);
  rules_invoke_event('rules_braintree_event_subscription_went_active', $user, $planid);
}
