<?php

/**
 * @file
 * Necessary file for declaring the Rules examples module. See
 * rules_braintree.rules.inc for the actual rules plugins.
 */

/**
 * Implements of hook_cb_subscription_charged_unsuccessfully().
 */
function rules_braintree_cb_subscription_canceled($user) {
  rules_invoke_event('rules_braintree_event_subscription_canceled', $user);
}

/**
 * Implements of hook_cb_subscription_charged_unsuccessfully().
 */
function rules_braintree_cb_subscription_charged_successfully($user) {
  rules_invoke_event('rules_braintree_event_subscription_charged_successfully', $user);
}

/**
 * Implements of hook_cb_subscription_charged_unsuccessfully().
 */
function rules_braintree_cb_subscription_charged_unsuccessfully($user) {
  rules_invoke_event('rules_braintree_event_subscription_charged_unsuccessfully', $user);
}

/**
 * Implements of hook_cb_subscription_expired().
 */
function rules_braintree_cb_subscription_expired($user) {
  rules_invoke_event('rules_braintree_event_subscription_expired', $user);
}

/**
 * Implements of hook_cb_subscription_trial_ended().
 */
function rules_braintree_cb_subscription_trial_ended($user) {
  rules_invoke_event('rules_braintree_event_subscription_trial_ended', $user);
}

/**
 * Implements of hook_cb_subscription_went_past_due().
 */
function rules_braintree_cb_subscription_went_past_due($user) {
  rules_invoke_event('rules_braintree_event_subscription_went_past_due', $user);
}

/**
 * Implements of hook_cb_subscription_went_active().
 */
function rules_braintree_cb_subscription_went_active($user) {
  rules_invoke_event('rules_braintree_event_subscription_went_active', $user);
}

function rules_braintree_menu() {
  $items['sub'] = array(
    'title' => 'sub',
    'type' => MENU_CALLBACK,
    'page callback' => 'rules_braintree_sub',
    'access arguments' => array('access content'), 
  );
  return $items;
}
function rules_braintree_sub() {
  $sub = commerce_braintree_subscription_get_by_id ("9vsq2m");
//$sub = commerce_braintree_subscription_get_by_id ("kfbs8b");
  //print_r($sub);
  dpm($sub);
  return '<h1>asd</h1>';
}