<?php

/**
 * Implementation of hook_cb_subscription_canceled().
 * Module : commerce_braintree
 */
function commerce_braintree_example_cb_subscription_went_active($kind, $sid) {
  
  $sub    = commerce_braintree_subscription_get_by_id($sid);
  $cus    = commerce_braintree_customer_get_by_token($sub->token);
  $orders = commerce_braintree_get_orders_by_uid($cus);
  foreach ($orders as $id) {
    $order = commerce_order_load($order);
    $plan  = commerce_braintree_planid_get($order);
    if ($plan) {
      commerce_order_status_update($order,"completed");
      break;
    }
  }
//  $sub = commerce_braintree_subscription_get_by_id($sid);
//  $cus = commerce_braintree_customer_get_by_token($sub->paymentMethodToken);
//  $uid = $cus->_ids[0];
//  db_insert('users_roles')
//    ->fields(array('uid' => $uid, 'rid' => 3))
//    ->execute();
}

function commerce_braintree_example_cb_subscription_charged_successfully($kind, $sid) {
  $sub = commerce_braintree_subscription_get_by_id($sid);
  $cus = commerce_braintree_customer_get_by_token($sub->paymentMethodToken);
  $uid = $cus->_ids[0];
  db_insert('users_roles')
    ->fields(array('uid' => $uid, 'rid' => 1))
    ->execute();
}

function commerce_braintree_example_menu() {
  $items = array();
//  $items['user/%user/customer'] = array(
//    'title' => 'Customer Braintree',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('commerce_braintree_example_form_customer'),
//    'access callback' => 'commerce_braintree_example_customer_acess',
//    'type' => MENU_LOCAL_TASK,
//    'file' => 'commerce_braintree_example.inc',
//  );
  return $items;
}

function commerce_braintree_example_customer_acess() {
  global $user;
  if (!commerce_braintree_customer_get($user->uid)) {
    return FALSE;
  }
  return TRUE;  
}