<?php

/**
 * Implementation of hook_views_api().
 */

define('LOG_SSL_REQUEST', 'request');
define('LOG_SSL_RESPONSE', 'response');

function commerce_braintree_log_views_api() {     
  return array(         
    'api' => '3.0-alpha1',         
    'path' => drupal_get_path('module', 'commerce_braintree_log') . '/views',     
  ); 
}

/**
 * Implementation of hook_menu().
 */

function commerce_braintree_log_menu() {
  $items['admin/commerce/braintree/log/detail/%'] = array(
    'title' => 'Details',
    'page callback' => 'commerce_braintree_log_detail',
    'page arguments' => array(5),
    'access arguments' => array('access braintree log'),
    'file' => 'commerce_braintree_log.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * 
 * Implementation of hook_permission().
 */
function commerce_braintree_log_permission() {
  return array(
    'access braintree log' => array(
      'title' => t('Access braintree log'), 
      'description' => t('Views detail braintree log.'),
    ),
  );
}

///**
// * Implementation of hook_cb_send_data_braintree().
// */
//function commerce_braintree_log_cb_send_data_braintree($data, $action, $message) {
//  $log = new stdClass();
//  $log->data = $data;
//  $log->action = "SEND: " . $action;
//  $log->message = $message;
//  commerce_braintree_log_save($log);
//}
//
///**
// * Implementation of hook_cb_receive_data_braintree().
// */
//function commerce_braintree_log_cb_receive_data_braintree($data, $action, $message) {
//  $log = new stdClass();
//  $log->data = $data;
//  $log->action = "RECV: " . $action;
//  $log->message = $message;
//  commerce_braintree_log_save($log);
//}

/**
 * Save log to database
 * @param stdClass $log
 */
function commerce_braintree_log_save(stdClass $log) {
  $record = array();
  $record['uid'] = isset($log->uid) ? $log->uid : $GLOBALS['user']->uid;
  $record['action'] = isset($log->action) ? $log->action : 'default';
  $record['message'] = isset($log->message) ? $log->message : '';
  $record['data'] = isset($log->data) ? serialize($log->data) : '';
  $record['hostname'] = ip_address();
  $record['timestamp'] = REQUEST_TIME;
  drupal_write_record("commerce_braintree_log", $record);
}

function commerce_braintree_log_ssl($data, $action) {
  $log = new stdClass();
  $log->uid = $GLOBALS['user']->uid;
  $log->action = $action;
  
  if ($action == LOG_SSL_REQUEST) {
//    dsm($data);
    $request_data = Braintree_Xml_Parser::arrayFromXml($data);
    $keys = array_keys($request_data);
    foreach ($keys as $key) {
      if ($key == 'creditCard') {
        $credit_card = $request_data[$key];
        $request_data[$key] = commerce_braintree_creditcard_mask($credit_card);
        break;
      }
    }
//    dsm($request_data);
    $data = Braintree_Xml_Generator::arrayToXml($request_data);
    dsm($data);
  }
  $log->data = $data;
  commerce_braintree_log_save($log);
}